version: '3.5'

services:
  integration_tests:
    container_name: integration_tests
    build:
      context: ../
      dockerfile: integration_tests/integration_test.Dockerfile
    depends_on:
      - events-postgres-dev
    networks:
      - test_network
